name: Release

on:
    push:
        tags:
            - v*
    workflow_dispatch:

permissions:
    contents: write

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, ubuntu-latest, windows-2022]
                include:
                    - os: macos-latest
                      platform: mac
                    - os: ubuntu-latest
                      platform: linux
                    - os: windows-2022
                      platform: windows

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - uses: pnpm/action-setup@v4 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"
                  cache-dependency-path: |
                      pnpm-lock.yaml
                      discord-adapter-meme/pnpm-lock.yaml
            - name: Use MSVC
              uses: ilammy/msvc-dev-cmd@v1

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Install adapter dependencies
              run: pnpm -C discord-adapter-meme install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Install system dependencies (Linux)
              if: ${{ matrix.platform == 'linux' }}
              run: sudo apt-get update && sudo apt-get install -y libarchive-tools

            - name: Run Electron Builder (Windows)
              if: ${{ matrix.platform == 'windows' }}
              run: |
                  pnpm electron-builder --${{ matrix.platform }} --publish always
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Run Electron Builder (Linux)
              if: ${{ matrix.platform == 'linux' }}
              run: |
                  pnpm electron-builder --${{ matrix.platform }} --publish always
                  pnpm electron-builder --${{ matrix.platform }} pacman --publish always
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Run Electron Builder (macOS)
              if: ${{ matrix.platform == 'mac' }}
              run: |
                  pnpm electron-builder --${{ matrix.platform }} --publish always
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CSC_IDENTITY_AUTO_DISCOVERY: "false"
